// UI State actions
const SELECT_RESOURCE_TYPE = 'SELECT_RESOURCE_TYPE';
const SELECT_UNIT_TYPE = 'SELECT_UNIT_TYPE';
const SELECT_BUILDING_TYPE = 'SELECT_BUILDING_TYPE';
const SELECT_BUILDING = 'SELECT_BUILDING';
const SELECT_UNITS_NORMALIZED = 'SELECT_UNITS_NORMALIZED';
const SELECT_DATA_SOURCE = 'SELECT_DATA_SOURCE';
const TOGGLE_FILTER = 'TOGGLE_FILTER';

const GET_BUILDING_DATA = 'GET_BUILDING_DATA';
const GET_BUILDING_DATA_SUCCESS = 'GET_BUILDING_DATA_SUCCESS';
const GET_BUILDING_DATA_FAILURE = 'GET_BUILDING_DATA_FAILURE`';

const LOAD_GEOJSON_DATA = 'LOAD_GEOJSON_DATA';
const LOAD_HISTORICAL_DATA = 'LOAD_HISTORICAL_DATA';

export default {
    SELECT_RESOURCE_TYPE,
    SELECT_UNIT_TYPE,
    SELECT_BUILDING_TYPE,
    SELECT_BUILDING,
    SELECT_UNITS_NORMALIZED,
    SELECT_DATA_SOURCE,
    TOGGLE_FILTER,

    GET_BUILDING_DATA,
    GET_BUILDING_DATA_SUCCESS,
    GET_BUILDING_DATA_FAILURE,

    LOAD_GEOJSON_DATA,
    LOAD_HISTORICAL_DATA
};
