const GET_BUILDING_DATA = 'GET_BUILDING_DATA';
const GET_BUILDING_DATA_SUCCESS = 'GET_BUILDING_DATA_SUCCESS';
const GET_BUILDING_DATA_FAILURE = 'GET_BUILDING_DATA_FAILURE`';

const LOAD_GEOJSON_DATA = 'LOAD_GEOJSON_DATA';

const ADD_GEOJSON_GRADIENT = 'ADD_GEOJSON_GRADIENT';

export default {
    GET_BUILDING_DATA,
    GET_BUILDING_DATA_SUCCESS,
    GET_BUILDING_DATA_FAILURE,
    LOAD_GEOJSON_DATA,
    ADD_GEOJSON_GRADIENT
};
